Feature: Sale close time
hiqdev/php-billing pull request #24
Opened 2021-03-12 15:25 UTC by SilverFire

2021-03-12 15:36 UTC, hiqsol approved these changes

2021-03-17 07:53 UTC, tafid approved these changes

2021-03-17 11:54 UTC, hiqsol commented on src/sale/SaleInterface.php
> +    public function cancelClosing(): void;
`reopen` ?

2021-03-17 12:45 UTC, strorch commented on tests/behat/bootstrap/BillingContext.php
> +                    return;
забагато умов щоб зробить 1 ретурн

2021-03-17 12:52 UTC, SilverFire commented on tests/behat/bootstrap/BillingContext.php
> +                    return;
Как бы ты переписал?

2021-03-17 12:55 UTC, SilverFire commented on src/sale/SaleInterface.php
> +    public function cancelClosing(): void;
`cancelClosing()` как по мне более явно описывает, что происходит

2021-03-17 13:02 UTC, strorch requested changes

2021-03-17 13:02 UTC, strorch commented on tests/behat/bootstrap/BillingContext.php
> +            if (str_contains($sale->getPlan()->getName(), $planName)
вот так

         if ($this->saleExists())) {
             return;
         }
         
         ...
         
         private function saleExists() 
         {
            return (str_contains($sale->getPlan()->getName(), $planName)&& $sale->getTime()->format(DATE_ATOM) === $saleDateTime->format(DATE_ATOM)
            && (
            ($saleCloseDate === null && $sale->getCloseTime() === null)
            ||
            ($saleCloseDate !== null && $sale->getCloseTime()->format(DATE_ATOM) === $saleCloseDateTime->format(DATE_ATOM))
            )
         }

2021-03-17 13:52 UTC, SilverFire commented on tests/behat/bootstrap/BillingContext.php
> +            if (str_contains($sale->getPlan()->getName(), $planName)
https://github.com/hiqdev/php-billing/commit/a9467cbee351bed402d3e6469ccb96f6b2aa0cd6

спасибо!

2021-03-17 14:33 UTC, merged