add new attributes
hiqdev/php-billing pull request #26
Opened 2021-07-27 11:11 UTC by bladeroot

2021-07-28 09:39 UTC, hiqsol commented on src/statement/Statement.php
> +    private DateTimeImmutable $date;
то же самое: зачем date если есть time

2021-07-28 09:39 UTC, strorch requested changes

2021-07-28 09:39 UTC, strorch commented on src/statement/Statement.php
> +        Money $amount
спочатку треба писать аргументи обов*язкові, потім - необов*язкові. ти ж цей клас руками не створиш адекватно

2021-07-29 08:57 UTC, hiqsol commented on src/bill/Bill.php
> +        DateTimeImmutable $month,
ты решил нам вообще всё нахер сломать?

2021-07-30 09:02 UTC, SilverFire commented
Поговорили, изменения в Bill нужно откатить

2021-07-30 10:57 UTC, SilverFire commented on src/statement/StatementBill.php
> +        DateTimeImmutable $month,
Затерялся один обязательный параметр среди опциональных

2021-08-02 15:05 UTC, SilverFire approved these changes

2021-08-02 15:05 UTC, merged