add func getTariffType
hiqdev/php-billing pull request #29
Opened 2021-08-20 06:50 UTC by bladeroot

2021-08-20 07:13 UTC, strorch approved these changes

2021-08-23 15:26 UTC, hiqsol requested changes

2021-08-23 15:26 UTC, hiqsol commented on src/statement/StatementBill.php
> +        return $this->tariffType;
а выше `tariff_type`

2021-08-26 14:19 UTC, SilverFire approved these changes

2021-08-30 06:16 UTC, merged