fix: add missed attribute and method
hiqdev/php-billing pull request #37
Opened 2021-11-12 17:17 UTC by bladeroot

2021-11-15 13:11 UTC, SilverFire requested changes

2021-11-15 13:11 UTC, SilverFire commented on src/statement/Statement.php
> +    public function setPlans(array $plans)
```suggestion
    /**
     * @param PlanInterface[]
     */
    public function setPlans(array $plans): void
```

+ import

2021-11-15 13:11 UTC, SilverFire commented on src/statement/Statement.php
> +    public function getPlans(): array
```suggestion
    /**
     * @return PlanInterface[]
     */
    public function getPlans(): array
```

2021-11-16 10:41 UTC, hiqsol approved these changes

2021-11-16 10:42 UTC, merged