add sale
hiqdev/php-billing pull request #60
Opened 2023-11-15 07:56 UTC by bladeroot

2023-12-07 13:28 UTC, SilverFire requested changes

2024-01-12 12:52 UTC, hiqsol approved these changes

2024-01-12 15:25 UTC, SilverFire approved these changes

2024-01-12 15:25 UTC, SilverFire commented on src/charge/modifiers/Leasing.php
> +    private function isFirstMonthInLeasingPassed(\DateTimeImmutable $time): bool
```suggestion
    private function isFirstMonthInLeasingPassed(DateTimeImmutable $time): bool
```

2024-01-12 15:25 UTC, SilverFire commented on src/charge/modifiers/event/LeasingWasStarted.php
> +    private function __construct(ChargeInterface $charge, \DateTimeImmutable $time)
Prefer `use DateTimeImmutable` instead of specifying FQCN in code.

2024-01-15 15:33 UTC, SilverFire approved these changes

2024-01-15 15:33 UTC, merged